---
- name: Playbook used to deploy wordpress and mariadb server
  hosts: all
  collections:
    - rhel.custombdd
  tasks:
    - name: Import a role
      ansible.builtin.import_role:
        name: bdd
